# Generated by Django 3.1.3 on 2020-12-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇letisim',
            name='message',
            field=models.CharField(max_length=50, verbose_name='mesajınızı bize detaylı olarak anlatınız'),
        ),
        migrations.AlterField(
            model_name='i̇letisim',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Hangi konu hakkında bizimle ilerişime geçmek istersiniz ?'),
        ),
    ]
