# Generated by Django 3.1.3 on 2020-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0002_auto_20201206_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇letisim',
            name='logo',
            field=models.ImageField(blank=True, default='album_logos/no-image.jpg', upload_to='album_logos'),
        ),
    ]
