# Generated by Django 3.1.3 on 2020-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0003_i̇letisim_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇letisim',
            name='logo',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
