# Generated by Django 3.1.3 on 2020-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0004_auto_20201206_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇letisim',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
